version: '3'
services:
  dashboards:
    image: ghcr.io/swarm-disc/dashboards:main
    platform: "linux/amd64"
    volumes:
      - ./cache:/home/panel-user/cache
    ports:
      - 80:5006
    command: panel serve src/geomagnetic-model-explorer.ipynb --allow-websocket-origin=* --warm --num-procs 1 --global-loading-spinner
    restart: always
    mem_limit: 20g
