channels:
  - conda-forge
dependencies:
  - conda-build
  - conda-verify
  - gcc
  - gfortran
  - python=3.10
  - pip
  - jupyter
  - cartopy
  - datashader
  - hvplot
  - pandas
  - panel
  - scipy
  - xarray
