[project]
name = "vires-dashboards"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "viresclient",
    "panel",
    "param",
    "nbconvert",
    "hvplot>=0.12.2",
]

[dependency-groups]
dev = [
    "watchfiles>=1.1.1",
]

[tool.uv.sources]
# viresclient = { path = "../../VirES-Python-Client", editable = true }
viresclient = { git = "https://github.com/ESA-VirES/VirES-Python-Client.git", rev = "staging" }
